--------------------------------------------------------
--  File created - Tuesday-March-13-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence ACCOUNTS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "JOSEPHCUELLAR2662"."ACCOUNTS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 201 CACHE 20 NOORDER  NOCYCLE   ;
--------------------------------------------------------
--  DDL for Sequence ACCOUNTS_USERS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "JOSEPHCUELLAR2662"."ACCOUNTS_USERS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 141 CACHE 20 NOORDER  NOCYCLE   ;
--------------------------------------------------------
--  DDL for Sequence FLASH_CARDS_PK
--------------------------------------------------------

   CREATE SEQUENCE  "JOSEPHCUELLAR2662"."FLASH_CARDS_PK"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE   ;
--------------------------------------------------------
--  DDL for Sequence FLASH_CARDS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "JOSEPHCUELLAR2662"."FLASH_CARDS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE   ;
--------------------------------------------------------
--  DDL for Sequence LOG_TABLE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "JOSEPHCUELLAR2662"."LOG_TABLE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE   ;
--------------------------------------------------------
--  DDL for Sequence USERS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "JOSEPHCUELLAR2662"."USERS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 161 CACHE 20 NOORDER  NOCYCLE   ;
--------------------------------------------------------
--  DDL for Table ACCOUNTS
--------------------------------------------------------

  CREATE TABLE "JOSEPHCUELLAR2662"."ACCOUNTS" 
   (	"ACCOUNTID" NUMBER(*,0), 
	"BALANCE" NUMBER(9,1), 
	"STATUS" NUMBER(*,0), 
	"ACCOUNTNAME" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ACCOUNTS_USERS
--------------------------------------------------------

  CREATE TABLE "JOSEPHCUELLAR2662"."ACCOUNTS_USERS" 
   (	"ACOUNTSUSERSID" NUMBER(*,0), 
	"ACCOUNTNAME" VARCHAR2(255 BYTE), 
	"USERNAME" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table FLASH_CARDS
--------------------------------------------------------

  CREATE TABLE "JOSEPHCUELLAR2662"."FLASH_CARDS" 
   (	"FC_ID" NUMBER, 
	"FC_QUESTION" VARCHAR2(400 BYTE), 
	"FC_ANSWER" VARCHAR2(400 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table LOG_TABLE
--------------------------------------------------------

  CREATE TABLE "JOSEPHCUELLAR2662"."LOG_TABLE" 
   (	"LOGID" NUMBER, 
	"ACCOUNTNAME" VARCHAR2(255 BYTE), 
	"ACCOUNT_TIME_CREATION" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "JOSEPHCUELLAR2662"."USERS" 
   (	"USERID" NUMBER(*,0), 
	"FIRSTNAME" VARCHAR2(255 BYTE), 
	"LASTNAME" VARCHAR2(255 BYTE), 
	"USERNAME" VARCHAR2(255 BYTE), 
	"PASSWORD" VARCHAR2(255 BYTE), 
	"USER_TYPE" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into JOSEPHCUELLAR2662.ACCOUNTS
SET DEFINE OFF;
Insert into JOSEPHCUELLAR2662.ACCOUNTS (ACCOUNTID,BALANCE,STATUS,ACCOUNTNAME) values (189,900,1,'dmoney_account');
Insert into JOSEPHCUELLAR2662.ACCOUNTS (ACCOUNTID,BALANCE,STATUS,ACCOUNTNAME) values (188,100,1,'sarah_account');
REM INSERTING into JOSEPHCUELLAR2662.ACCOUNTS_USERS
SET DEFINE OFF;
Insert into JOSEPHCUELLAR2662.ACCOUNTS_USERS (ACOUNTSUSERSID,ACCOUNTNAME,USERNAME) values (130,'sarah_account','sarah');
Insert into JOSEPHCUELLAR2662.ACCOUNTS_USERS (ACOUNTSUSERSID,ACCOUNTNAME,USERNAME) values (131,'dmoney_account','dmoney');
REM INSERTING into JOSEPHCUELLAR2662.FLASH_CARDS
SET DEFINE OFF;
Insert into JOSEPHCUELLAR2662.FLASH_CARDS (FC_ID,FC_QUESTION,FC_ANSWER) values (1,'Is this working','It better');
Insert into JOSEPHCUELLAR2662.FLASH_CARDS (FC_ID,FC_QUESTION,FC_ANSWER) values (2,'Is this still working','Of course it is');
REM INSERTING into JOSEPHCUELLAR2662.LOG_TABLE
SET DEFINE OFF;
Insert into JOSEPHCUELLAR2662.LOG_TABLE (LOGID,ACCOUNTNAME,ACCOUNT_TIME_CREATION) values (3,'test_accountname',to_date('13-MAR-18','DD-MON-RR'));
Insert into JOSEPHCUELLAR2662.LOG_TABLE (LOGID,ACCOUNTNAME,ACCOUNT_TIME_CREATION) values (4,'test_accountname',to_date('13-MAR-18','DD-MON-RR'));
Insert into JOSEPHCUELLAR2662.LOG_TABLE (LOGID,ACCOUNTNAME,ACCOUNT_TIME_CREATION) values (25,'dmoney_account',to_date('13-MAR-18','DD-MON-RR'));
Insert into JOSEPHCUELLAR2662.LOG_TABLE (LOGID,ACCOUNTNAME,ACCOUNT_TIME_CREATION) values (22,'dmoney_account',to_date('13-MAR-18','DD-MON-RR'));
Insert into JOSEPHCUELLAR2662.LOG_TABLE (LOGID,ACCOUNTNAME,ACCOUNT_TIME_CREATION) values (2,'jcuellar_acc1',to_date('13-MAR-18','DD-MON-RR'));
Insert into JOSEPHCUELLAR2662.LOG_TABLE (LOGID,ACCOUNTNAME,ACCOUNT_TIME_CREATION) values (21,'dmoney_acc',to_date('13-MAR-18','DD-MON-RR'));
Insert into JOSEPHCUELLAR2662.LOG_TABLE (LOGID,ACCOUNTNAME,ACCOUNT_TIME_CREATION) values (1,'test_accountname',to_date('13-MAR-18','DD-MON-RR'));
Insert into JOSEPHCUELLAR2662.LOG_TABLE (LOGID,ACCOUNTNAME,ACCOUNT_TIME_CREATION) values (5,'test_accountname',to_date('13-MAR-18','DD-MON-RR'));
Insert into JOSEPHCUELLAR2662.LOG_TABLE (LOGID,ACCOUNTNAME,ACCOUNT_TIME_CREATION) values (23,'dmoney_account',to_date('13-MAR-18','DD-MON-RR'));
Insert into JOSEPHCUELLAR2662.LOG_TABLE (LOGID,ACCOUNTNAME,ACCOUNT_TIME_CREATION) values (24,'dmoney_account',to_date('13-MAR-18','DD-MON-RR'));
REM INSERTING into JOSEPHCUELLAR2662.USERS
SET DEFINE OFF;
Insert into JOSEPHCUELLAR2662.USERS (USERID,FIRSTNAME,LASTNAME,USERNAME,PASSWORD,USER_TYPE) values (153,'Joseph','Cuellar','joseph','1234','admin');
Insert into JOSEPHCUELLAR2662.USERS (USERID,FIRSTNAME,LASTNAME,USERNAME,PASSWORD,USER_TYPE) values (155,'Sarah','Cuellar','sarah','1234','customer');
Insert into JOSEPHCUELLAR2662.USERS (USERID,FIRSTNAME,LASTNAME,USERNAME,PASSWORD,USER_TYPE) values (154,'Joshua','Cuellar','josh','1234','employee');
Insert into JOSEPHCUELLAR2662.USERS (USERID,FIRSTNAME,LASTNAME,USERNAME,PASSWORD,USER_TYPE) values (156,'Daniel','Cuellar','dmoney','1234','customer');
--------------------------------------------------------
--  DDL for Index UC_USERNAME
--------------------------------------------------------

  CREATE UNIQUE INDEX "JOSEPHCUELLAR2662"."UC_USERNAME" ON "JOSEPHCUELLAR2662"."USERS" ("USERNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index AC_ACCOUNTNAME
--------------------------------------------------------

  CREATE UNIQUE INDEX "JOSEPHCUELLAR2662"."AC_ACCOUNTNAME" ON "JOSEPHCUELLAR2662"."ACCOUNTS" ("ACCOUNTNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger ACCOUNTS_ON_INSERT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "JOSEPHCUELLAR2662"."ACCOUNTS_ON_INSERT" 
    BEFORE INSERT ON ACCOUNTS
    FOR EACH ROW
BEGIN
    SELECT ACCOUNTS_SEQ.NEXTVAL
    INTO :NEW.AccountID
    FROM DUAL;
END;
/
ALTER TRIGGER "JOSEPHCUELLAR2662"."ACCOUNTS_ON_INSERT" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ACCOUNTS_USERS_ON_INSERT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "JOSEPHCUELLAR2662"."ACCOUNTS_USERS_ON_INSERT" 
    BEFORE INSERT ON ACCOUNTS_USERS
    FOR EACH ROW
BEGIN 
    SELECT ACCOUNTS_USERS_SEQ.NEXTVAL
    INTO :NEW.ACOUNTSUSERSID
    FROM DUAL;
END;
/
ALTER TRIGGER "JOSEPHCUELLAR2662"."ACCOUNTS_USERS_ON_INSERT" ENABLE;
--------------------------------------------------------
--  DDL for Trigger FLASH_CARD_ON_INSERT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "JOSEPHCUELLAR2662"."FLASH_CARD_ON_INSERT" 
    BEFORE INSERT ON FLASH_CARDS
    FOR EACH ROW
BEGIN
    SELECT FLASH_CARDS_SEQ.NEXTVAL
    INTO :NEW.FC_ID
    FROM DUAL;
END;
/
ALTER TRIGGER "JOSEPHCUELLAR2662"."FLASH_CARD_ON_INSERT" ENABLE;
--------------------------------------------------------
--  DDL for Trigger LOG_TABLE_INSERT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "JOSEPHCUELLAR2662"."LOG_TABLE_INSERT" 
    BEFORE INSERT ON LOG_TABLE
    FOR EACH ROW
BEGIN
    SELECT LOG_TABLE_SEQ.NEXTVAL
    INTO :NEW.LOGID
    FROM DUAL;
END;
/
ALTER TRIGGER "JOSEPHCUELLAR2662"."LOG_TABLE_INSERT" ENABLE;
--------------------------------------------------------
--  DDL for Trigger USER_ON_INSERT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "JOSEPHCUELLAR2662"."USER_ON_INSERT" 
    BEFORE INSERT ON USERS
    FOR EACH ROW
BEGIN
    SELECT USERS_SEQ.NEXTVAL
    INTO :NEW.UserID
    FROM DUAL;
END;
/
ALTER TRIGGER "JOSEPHCUELLAR2662"."USER_ON_INSERT" ENABLE;
--------------------------------------------------------
--  DDL for Procedure TRANSFER
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "JOSEPHCUELLAR2662"."TRANSFER" (
    ACC_NAME_FROM IN ACCOUNTS.ACCOUNTNAME%TYPE,
    ACC_NAME_TO IN ACCOUNTS.ACCOUNTNAME%TYPE,
    AMOUNT IN ACCOUNTS.BALANCE%TYPE
) AS
BEGIN
    UPDATE ACCOUNTS
    SET BALANCE = BALANCE - AMOUNT
    WHERE ACCOUNTNAME = ACC_NAME_FROM AND BALANCE > AMOUNT AND STATUS = 1;

    UPDATE ACCOUNTS
    SET BALANCE = BALANCE + AMOUNT
    WHERE ACCOUNTNAME = ACC_NAME_TO AND STATUS = 1;
END;

/
--------------------------------------------------------
--  Constraints for Table FLASH_CARDS
--------------------------------------------------------

  ALTER TABLE "JOSEPHCUELLAR2662"."FLASH_CARDS" ADD PRIMARY KEY ("FC_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ACCOUNTS
--------------------------------------------------------

  ALTER TABLE "JOSEPHCUELLAR2662"."ACCOUNTS" ADD CONSTRAINT "AC_ACCOUNTNAME" UNIQUE ("ACCOUNTNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "JOSEPHCUELLAR2662"."ACCOUNTS" ADD PRIMARY KEY ("ACCOUNTID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ACCOUNTS_USERS
--------------------------------------------------------

  ALTER TABLE "JOSEPHCUELLAR2662"."ACCOUNTS_USERS" ADD PRIMARY KEY ("ACOUNTSUSERSID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table LOG_TABLE
--------------------------------------------------------

  ALTER TABLE "JOSEPHCUELLAR2662"."LOG_TABLE" ADD PRIMARY KEY ("LOGID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "JOSEPHCUELLAR2662"."USERS" ADD CONSTRAINT "UC_USERNAME" UNIQUE ("USERNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "JOSEPHCUELLAR2662"."USERS" ADD PRIMARY KEY ("USERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ACCOUNTS_USERS
--------------------------------------------------------

  ALTER TABLE "JOSEPHCUELLAR2662"."ACCOUNTS_USERS" ADD FOREIGN KEY ("ACCOUNTNAME")
	  REFERENCES "JOSEPHCUELLAR2662"."ACCOUNTS" ("ACCOUNTNAME") ON DELETE CASCADE ENABLE;
  ALTER TABLE "JOSEPHCUELLAR2662"."ACCOUNTS_USERS" ADD FOREIGN KEY ("USERNAME")
	  REFERENCES "JOSEPHCUELLAR2662"."USERS" ("USERNAME") ON DELETE CASCADE ENABLE;
